name: Continuous Integration

on: [push, pull_request]

env:
  RUST_TOOLCHAIN_VERSION: 1.55.0

jobs:
  check:
    name: Check
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Setup the Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
          override: true
      
      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: ci

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Setup the Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: ci

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  format:
    name: Format
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Setup the Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
          override: true
          components: rustfmt

      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: ci

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Setup the Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
          override: true
          components: clippy

      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: ci

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
